# Generated by Django 5.1.15 on 2026-07-10 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('unit', models.CharField(choices=[('sht', 'Штук'), ('m', 'Метр'), ('m2', 'Квадратный метр'), ('izdelie', 'Изделие'), ('dona', 'Дона')], max_length=20)),
                ('deadline', models.DateField()),
                ('material', models.CharField(blank=True, default='', max_length=100)),
                ('comment', models.TextField(blank=True, default='')),
                ('drawing', models.ImageField(blank=True, null=True, upload_to='orders/drawings/')),
                ('status', models.CharField(choices=[('new', 'Янги'), ('awaiting_material', 'Материал кутилмоқда'), ('sent_to_worker', 'Ишчига юборилган'), ('accepted_by_worker', 'Ишчи қабул қилди'), ('worker_refused', 'Ишчи рад этди'), ('in_progress', 'Иш жараёнида'), ('awaiting_confirmation', 'Тасдиқлаш кутилмоқда'), ('ready', 'Тайёр'), ('delivered', 'Мижозга берилди'), ('cancelled', 'Бекор қилинди')], db_index=True, default='new', max_length=30)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Тўлов қилинмаган'), ('partial', 'Қисман тўланган'), ('paid', 'Тўланган')], db_index=True, default='unpaid', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('material_shortage', models.BooleanField(default=False)),
                ('is_overdue', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='clients.client')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='warehouse.finishedproduct')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'deadline'], name='orders_orde_status_be8e23_idx'), models.Index(fields=['client', 'status'], name='orders_orde_client__7fa500_idx'), models.Index(fields=['worker', 'status'], name='orders_orde_worker__2b28f9_idx')],
            },
        ),
    ]
