# Generated by Django 5.1.15 on 2026-07-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='order',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='orders/'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('awaiting_material', 'Ожидает материала'), ('sent_to_worker', 'Отправлен работнику'), ('accepted', 'Принят работником'), ('worker_refused', 'Работник отказался'), ('in_progress', 'В работе'), ('awaiting_confirmation', 'Ожидает подтверждения'), ('ready', 'Готов'), ('delivered', 'Выдан клиенту'), ('cancelled', 'Отменен')], db_index=True, default='new', max_length=50),
        ),
    ]
