# Generated by Django 5.1.15 on 2026-07-20 14:40

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='orders/', validators=[apps.core.validators.validate_file_size]),
        ),
    ]
