# Generated by Django 5.1.15 on 2026-07-22 12:21

from django.db import migrations, models
from django.db.models import F


def backfill_delivered_at(apps, schema_editor):
    """
    Проставляет delivered_at существующим выданным заказам.

    Истинного времени выдачи для старых записей нет — берём updated_at как
    наилучший доступный прокси (именно по нему отчёты раньше и считали COGS).
    Так исторические отчёты не «прыгнут» после деплоя.
    """
    Order = apps.get_model('orders', 'Order')
    Order.objects.filter(status='delivered', delivered_at__isnull=True).update(
        delivered_at=F('updated_at'),
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_quantity_alter_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_delivered_at, noop_reverse),
    ]
