# Generated by Django 5.1.15 on 2026-07-27 11:44

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_client_address_alter_client_comment_and_more'),
        ('companies', '0004_alter_company_is_active_alter_company_name'),
        ('orders', '0008_order_delivered_at'),
        ('warehouse', '0006_alter_finishedproduct_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='clients.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='custom_product_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название товара (вручную)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Выдан клиенту'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Не оплачено'), ('partial', 'Частичная оплата'), ('paid', 'Оплачено')], default='unpaid', max_length=50, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='orders/', validators=[apps.core.validators.validate_file_size], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='warehouse.finishedproduct', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('awaiting_material', 'Ожидает материала'), ('sent_to_worker', 'Отправлен работнику'), ('accepted', 'Принят работником'), ('worker_refused', 'Работник отказался'), ('in_progress', 'В работе'), ('awaiting_confirmation', 'Ожидает подтверждения'), ('ready', 'Готов'), ('delivered', 'Выдан клиенту'), ('cancelled', 'Отменен')], db_index=True, default='new', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сумма заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='unit',
            field=models.CharField(max_length=20, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='Работник'),
        ),
    ]
