# Generated by Django 5.1.15 on 2026-07-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_client_alter_order_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='unit',
            field=models.CharField(choices=[('sht', 'Штук'), ('m', 'Метр'), ('m2', 'Квадратный метр'), ('izdelie', 'Изделие'), ('dona', 'Дона')], max_length=20, verbose_name='Единица измерения'),
        ),
    ]
