# Generated by Django 5.1.15 on 2026-07-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='unit',
            field=models.CharField(choices=[('sht', 'Штук'), ('m', 'Метр'), ('m2', 'Квадратный метр'), ('izdelie', 'Изделие'), ('dona', 'Дона'), ('kg', 'Килограмм'), ('m3', 'Кубический метр')], default='izdelie', max_length=20, verbose_name='Единица измерения'),
        ),
    ]
