# Generated by Django 5.1.15 on 2026-08-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Себестоимость на момент выдачи'),
        ),
    ]
