# Generated by Django 5.1.15 on 2026-08-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_cost_price_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Тўлов қилинмаган'), ('partial', 'Қисман тўланган'), ('paid', 'Тўланган')], default='unpaid', max_length=50, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Янги'), ('awaiting_material', 'Материал кутилмоқда'), ('sent_to_worker', 'Ишчига юборилган'), ('accepted', 'Қабул қилинди'), ('worker_refused', 'Рад этилди'), ('in_progress', 'Жараёнда'), ('awaiting_confirmation', 'Тасдиқлаш кутилмоқда'), ('ready', 'Тайёр'), ('delivered', 'Мижозга берилди'), ('cancelled', 'Бекор қилинди')], db_index=True, default='new', max_length=50, verbose_name='Статус'),
        ),
    ]
