# Generated by Django 5.1.15 on 2026-09-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_payment_status_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_due_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Срок оплаты'),
        ),
    ]
