# Generated by Django 5.1.15 on 2026-09-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_payment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='unit',
            field=models.CharField(choices=[('sht', 'Штук'), ('m', 'Метр'), ('m2', 'Квадратный метр'), ('izdelie', 'Изделие'), ('kg', 'Килограмм'), ('m3', 'Кубический метр')], default='izdelie', max_length=20, verbose_name='Единица измерения'),
        ),
    ]
