# Generated by Django 5.1.15 on 2026-07-12 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Кутилмоқда'), ('accepted', 'Қабул қилинди'), ('refused', 'Рад этилди'), ('in_progress', 'Жараёнда'), ('completed', 'Бажарилди'), ('confirmed', 'Тасдиқланди'), ('rejected', 'Рад этилди'), ('cancelled', 'Бекор қилинди')], db_index=True, default='pending', max_length=20)),
                ('refusal_reason', models.CharField(blank=True, choices=[('material_insufficient', 'Материал етарли эмас'), ('no_time', 'Вақтим йўқ'), ('wrong_size', 'Ўлчам нотўғри'), ('need_helper', 'Ёрдамчи керак'), ('equipment_busy', 'Ускуна банд'), ('other', 'Бошқа сабаб')], default='', max_length=30)),
                ('refusal_comment', models.TextField(blank=True, default='')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_comment', models.TextField(blank=True, default='')),
                ('is_self_assigned', models.BooleanField(default=False)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_tasks', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='orders.order')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('unit', models.CharField(choices=[('sht', 'Штук'), ('m', 'Метр'), ('m2', 'Квадратный метр'), ('izdelie', 'Изделие'), ('dona', 'Дона')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='production/work_photos/')),
                ('comment', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('awaiting_confirmation', 'Тасдиқлаш кутилмоқда'), ('confirmed', 'Тасдиқланди'), ('rejected', 'Рад этилди')], db_index=True, default='awaiting_confirmation', max_length=30)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_works', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_records', to='warehouse.finishedproduct')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_records', to='production.task')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Record',
                'verbose_name_plural': 'Work Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['worker', 'status'], name='production__worker__6a4ed6_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'assigned_at'], name='production__status_fc6e5d_idx'),
        ),
        migrations.AddIndex(
            model_name='workrecord',
            index=models.Index(fields=['worker', 'status'], name='production__worker__de5d55_idx'),
        ),
        migrations.AddIndex(
            model_name='workrecord',
            index=models.Index(fields=['status', 'created_at'], name='production__status_ba3d41_idx'),
        ),
    ]
