# Generated by Django 5.1.4 on 2026-07-10 11:42

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        ('warehouse', '0002_alter_finishedproduct_cost_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecord',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AddConstraint(
            model_name='workrecord',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='work_record_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='workrecord',
            constraint=models.CheckConstraint(condition=models.Q(('labor_cost__gte', 0)), name='work_record_labor_cost_non_negative'),
        ),
    ]
