# Generated by Django 5.1.15 on 2026-07-16 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_task_created_at_alter_task_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-assigned_at'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='workrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запись о работе', 'verbose_name_plural': 'Записи о работе'},
        ),
    ]
