# Generated by Django 5.1.15 on 2026-07-20 14:40

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_alter_task_options_alter_workrecord_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecord',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='production/work_photos/', validators=[apps.core.validators.validate_file_size]),
        ),
    ]
