# Generated by Django 5.1.15 on 2026-07-27 11:44

import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_is_active_alter_company_name'),
        ('orders', '0009_alter_order_client_alter_order_comment_and_more'),
        ('production', '0005_alter_workrecord_photo'),
        ('warehouse', '0006_alter_finishedproduct_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Принято в работу'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Назначено'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Кем назначено'),
        ),
        migrations.AlterField(
            model_name='task',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершено'),
        ),
        migrations.AlterField(
            model_name='task',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Подтверждено'),
        ),
        migrations.AlterField(
            model_name='task',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Кем подтверждено'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_self_assigned',
            field=models.BooleanField(default=False, verbose_name='Взято работником самостоятельно'),
        ),
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='task',
            name='refusal_comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий к отказу'),
        ),
        migrations.AlterField(
            model_name='task',
            name='refusal_reason',
            field=models.CharField(blank=True, choices=[('material_insufficient', 'Материал етарли эмас'), ('no_time', 'Вақтим йўқ'), ('wrong_size', 'Ўлчам нотўғри'), ('need_helper', 'Ёрдамчи керак'), ('equipment_busy', 'Ускуна банд'), ('other', 'Бошқа сабаб')], default='', max_length=30, verbose_name='Причина отказа'),
        ),
        migrations.AlterField(
            model_name='task',
            name='rejection_comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий к отклонению'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Кутилмоқда'), ('accepted', 'Қабул қилинди'), ('refused', 'Рад этилди'), ('in_progress', 'Жараёнда'), ('completed', 'Бажарилди'), ('confirmed', 'Тасдиқланди'), ('rejected', 'Рад этилди'), ('cancelled', 'Бекор қилинди')], db_index=True, default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Работник'),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_records', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Подтверждено'),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_works', to=settings.AUTH_USER_MODEL, verbose_name='Кем подтверждено'),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Стоимость работы'),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='production/work_photos/', validators=[apps.core.validators.validate_file_size], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_records', to='warehouse.finishedproduct', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', verbose_name='Причина отклонения'),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='status',
            field=models.CharField(choices=[('awaiting_confirmation', 'Тасдиқлаш кутилмоқда'), ('confirmed', 'Тасдиқланди'), ('rejected', 'Рад этилди')], db_index=True, default='awaiting_confirmation', max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_records', to='production.task', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='unit',
            field=models.CharField(choices=[('sht', 'Штук'), ('m', 'Метр'), ('m2', 'Квадратный метр'), ('izdelie', 'Изделие'), ('dona', 'Дона')], max_length=20, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_records', to=settings.AUTH_USER_MODEL, verbose_name='Работник'),
        ),
    ]
