# Generated by Django 5.1.15 on 2026-07-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_alter_task_accepted_at_alter_task_assigned_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecord',
            name='unit',
            field=models.CharField(choices=[('sht', 'Штук'), ('m', 'Метр'), ('m2', 'Квадратный метр'), ('izdelie', 'Изделие'), ('dona', 'Дона'), ('kg', 'Килограмм'), ('m3', 'Кубический метр')], max_length=20, verbose_name='Единица измерения'),
        ),
    ]
