# Generated by Django 5.1.15 on 2026-08-02 12:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_alter_workrecord_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='defect_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Брак'),
        ),
    ]
