# Generated by Django 5.1.15 on 2026-08-02 13:16

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_workrecord_defect_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('image', models.ImageField(upload_to='production/work_photos/', validators=[apps.core.validators.validate_file_size], verbose_name='Фото')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='production.workrecord', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Фото работы',
                'verbose_name_plural': 'Фото работ',
                'ordering': ['id'],
            },
        ),
    ]
