# Generated by Django 5.1.15 on 2026-08-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_move_work_photo_to_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='operation',
            field=models.CharField(blank=True, choices=[('cutting', 'Кесиш'), ('polishing', 'Сийлаш'), ('mounting', 'Монтаж'), ('packing', 'Қутлаш'), ('other', 'Бошқа')], max_length=20, null=True, verbose_name='Операция'),
        ),
    ]
