# Generated by Django 5.1.15 on 2026-08-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_workrecord_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecord',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Годное количество'),
        ),
    ]
