# Generated by Django 5.1.15 on 2026-09-07 11:20

import apps.core.validators
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_alter_workrecord_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='tasks/attachments/%Y/%m/', validators=[apps.core.validators.validate_file_size, apps.core.validators.validate_attachment_extension], verbose_name='Вложение (чертёж)'),
        ),
        migrations.AddField(
            model_name='task',
            name='attachment_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Имя файла вложения'),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Срок выполнения'),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='task',
            name='size',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Размер изделия'),
        ),
        migrations.AddField(
            model_name='task',
            name='thickness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Толщина, мм'),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Название задачи'),
        ),
        migrations.AddField(
            model_name='task',
            name='workshop',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Цех'),
        ),
    ]
