# Generated by Django 5.1.15 on 2026-09-08 05:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_task_attachment_task_attachment_name_task_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='planned_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Плановое количество'),
        ),
        migrations.AddField(
            model_name='task',
            name='planned_unit',
            field=models.CharField(blank=True, choices=[('sht', 'Штук'), ('m', 'Метр'), ('m2', 'Квадратный метр'), ('izdelie', 'Изделие'), ('dona', 'Дона'), ('kg', 'Килограмм'), ('m3', 'Кубический метр')], default='', max_length=20, verbose_name='Единица планового количества'),
        ),
    ]
