# Generated by Django 5.1.15 on 2026-09-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_task_planned_quantity_task_planned_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='planned_unit',
            field=models.CharField(blank=True, choices=[('sht', 'Штук'), ('m', 'Метр'), ('m2', 'Квадратный метр'), ('izdelie', 'Изделие'), ('kg', 'Килограмм'), ('m3', 'Кубический метр')], default='', max_length=20, verbose_name='Единица планового количества'),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='unit',
            field=models.CharField(choices=[('sht', 'Штук'), ('m', 'Метр'), ('m2', 'Квадратный метр'), ('izdelie', 'Изделие'), ('kg', 'Килограмм'), ('m3', 'Кубический метр')], max_length=20, verbose_name='Единица измерения'),
        ),
    ]
