# Generated by Django 5.1.15 on 2026-09-10 05:49

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_alter_task_planned_unit_alter_workrecord_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='refusal_attachment',
            field=models.FileField(blank=True, null=True, upload_to='tasks/attachments/%Y/%m/', validators=[apps.core.validators.validate_file_size, apps.core.validators.validate_attachment_extension], verbose_name='Илова к отказу (фото)'),
        ),
        migrations.AddField(
            model_name='task',
            name='refusal_attachment_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Имя файла отказа'),
        ),
    ]
