# Generated by Django 5.1.15 on 2026-07-14 10:42

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_bio_user_birth_date_user_department_and_more'),
        ('companies', '0002_backfill_default_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, default=apps.accounts.models.generate_access_key_code, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_keys', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_access_keys', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Access key',
                'verbose_name_plural': 'Access keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='accounts_ac_company_00f285_idx'), models.Index(fields=['user', 'status'], name='accounts_ac_user_id_ccf593_idx')],
            },
        ),
    ]
