# Generated by Django 5.1.15 on 2026-07-15 07:46

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_accesskey'),
        ('companies', '0003_alter_company_options_alter_company_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesskey',
            options={'ordering': ['-created_at'], 'verbose_name': 'Код доступа', 'verbose_name_plural': 'Коды доступа (Access Key)'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name'], 'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_keys', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_access_keys', to=settings.AUTH_USER_MODEL, verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Действует до'),
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='key',
            field=models.CharField(db_index=True, default=apps.accounts.models.generate_access_key_code, max_length=32, unique=True, verbose_name='Код доступа'),
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('used', 'Использован'), ('revoked', 'Отозван')], db_index=True, default='active', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Использован'),
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_keys', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
