# Generated by Django 5.1.15 on 2026-07-20 14:40

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_accesskey_options_alter_skill_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='', upload_to='avatars/', validators=[apps.core.validators.validate_file_size]),
        ),
    ]
