# Generated by Django 5.1.15 on 2026-07-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_by_owner',
            field=models.BooleanField(default=False),
        ),
    ]
