# Generated by Django 5.1.15 on 2026-07-24 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_blocked_by_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name'], 'verbose_name': 'Навык (специализация)', 'verbose_name_plural': 'Навыки (специализации)'},
        ),
    ]
