# Generated by Django 5.1.15 on 2026-07-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_skill_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('uz_cyrl', 'Ўзбекча'), ('ru', 'Русский'), ('ky', 'Кыргызча')], default='uz_cyrl', max_length=10),
        ),
    ]
