# Generated by Django 5.1.15 on 2026-07-25 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_kyrgyz_language'),
        ('companies', '0003_alter_company_options_alter_company_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('endpoint', models.URLField(max_length=500)),
                ('p256dh_key', models.CharField(max_length=255, verbose_name='P256DH ключ')),
                ('auth_key', models.CharField(max_length=255, verbose_name='Auth ключ')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push подписка',
                'verbose_name_plural': 'Push подписки',
                'ordering': ['-created_at'],
            },
        ),
    ]
