# Generated by Django 5.1.15 on 2026-07-27 11:44

import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_pushsubscription'),
        ('companies', '0004_alter_company_is_active_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushsubscription',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='endpoint',
            field=models.URLField(max_length=500, verbose_name='Адрес подписки'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Устройство'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название навыка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='', upload_to='avatars/', validators=[apps.core.validators.validate_file_size], verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', verbose_name='О сотруднике'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='blocked_by_owner',
            field=models.BooleanField(default=False, verbose_name='Заблокирован владельцем'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_create_workers',
            field=models.BooleanField(default=False, verbose_name='Может создавать работников'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_see_other_workers',
            field=models.BooleanField(default=False, verbose_name='Видит других работников'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_write_to_owner',
            field=models.BooleanField(default=False, verbose_name='Может писать владельцу'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Эл. почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приёма'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('uz_cyrl', 'Ўзбекча'), ('ru', 'Русский'), ('ky', 'Кыргызча')], default='uz_cyrl', max_length=10, verbose_name='Язык интерфейса'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Administrator'), ('owner', 'Egasi'), ('admin', 'Administrator'), ('worker', 'Ishchi')], db_index=True, default='worker', max_length=12, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='employees', to='accounts.skill', verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('on_leave', 'Taʼtilda'), ('suspended', 'Toʼxtatilgan')], db_index=True, default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
