# Generated by Django 5.1.15 on 2026-07-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_pushsubscription_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Administrator'), ('owner', 'Egasi'), ('admin', 'Administrator'), ('manager', 'Menejer'), ('worker', 'Ishchi')], db_index=True, default='worker', max_length=12, verbose_name='Роль'),
        ),
    ]
