# Generated by Django 5.1.15 on 2026-08-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupGate',
            fields=[
                ('id', models.PositiveIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Заглушка первичной настройки',
                'verbose_name_plural': 'Заглушки первичной настройки',
            },
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model('accounts', 'SetupGate').objects.get_or_create(pk=1),
            reverse_code=migrations.RunPython.noop,
        ),
    ]
