# Generated by Django 5.1.15 on 2026-09-08 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_setupgate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('jti', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='JTI токена')),
                ('fingerprint_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='Отпечаток устройства')),
                ('user_agent', models.CharField(blank=True, default='', max_length=400, verbose_name='Устройство')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сессия пользователя',
                'verbose_name_plural': 'Сессии пользователей',
                'ordering': ['-created_at'],
            },
        ),
    ]
