# Generated by Django 5.1.15 on 2026-09-12 13:44

"""
Убирает из данных удалённую роль `manager`.

Роль `manager` исключена из User.Role (ТЗ знает только owner/admin/worker),
но в базе могут остаться аккаунты с этим значением. Без переноса они попали бы
в «роль без прав»: ни один permission её больше не признаёт, и сотрудник
потерял бы доступ к системе, оставшись при этом активным.

Самый безопасный вариант — понизить такие аккаунты до `worker` (наименьшие
привилегии): прежняя роль была только на чтение и без финансов, поэтому worker
не выдаёт ни одного нового права. Логин и пароль сохраняются — вход работает.

Откат данных намеренно не восстанавливает `manager`: после понижения отличить
бывших manager от обычных worker уже невозможно.
"""
from django.db import migrations, models


def manager_to_worker(apps, schema_editor):
    """Переносит аккаунты с удалённой ролью manager в worker."""
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role='manager').update(role='worker')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_usersession'),
    ]

    operations = [
        # Данные переносим ДО сужения choices: значение, которого больше нет в
        # модели, не должно пережить обновление.
        migrations.RunPython(manager_to_worker, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Administrator'), ('owner', 'Egasi'), ('admin', 'Administrator'), ('worker', 'Ishchi')], db_index=True, default='worker', max_length=12, verbose_name='Роль'),
        ),
    ]
