services:
  web:
    build:
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=skladpro.settings.development
      - DEBUG=True

  nginx:
    ports:
      - "80:80"
