# Generated by Django 5.1.15 on 2026-07-16 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_alter_chatmessage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Сообщение чата', 'verbose_name_plural': 'Сообщения чата'},
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Беседа', 'verbose_name_plural': 'Беседы'},
        ),
        migrations.AlterModelOptions(
            name='conversationparticipant',
            options={'verbose_name': 'Участник беседы', 'verbose_name_plural': 'Участники беседы'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
    ]
