# Generated by Django 5.1.15 on 2026-07-27 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_is_active_alter_company_name'),
        ('messaging', '0007_alter_chatmessage_conversation'),
        ('orders', '0009_alter_order_client_alter_order_comment_and_more'),
        ('production', '0006_alter_task_accepted_at_alter_task_assigned_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='kind',
            field=models.CharField(choices=[('general', 'Общий чат компании'), ('direct', 'Личный диалог'), ('group', 'Групповой чат')], db_index=True, max_length=10, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='conversationparticipant',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='messaging.conversation', verbose_name='Беседа'),
        ),
        migrations.AlterField(
            model_name='conversationparticipant',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Прочитано до'),
        ),
        migrations.AlterField(
            model_name='conversationparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_participations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда прочитано'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='orders.order', verbose_name='Связанный заказ'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='production.task', verbose_name='Связанная задача'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_order', 'Янги буюртма'), ('new_expense', 'Янги харажат'), ('unpaid_client', 'Мижоз тўлов қилмади'), ('overdue_debt', 'Қарз муддати ўтди'), ('worker_refused', 'Ишчи рад этди'), ('work_awaiting', 'Иш тасдиқлашни кутмоқда'), ('cash_change', 'Касса ўзгариши'), ('report_ready', 'Ҳисобот тайёр'), ('task_assigned', 'Янги вазифа'), ('task_changed', 'Вазифа ўзгартирилди'), ('task_cancelled', 'Вазифа бекор қилинди'), ('work_confirmed', 'Иш тасдиқланди'), ('work_rejected', 'Иш рад этди'), ('new_message', 'Янги хабар'), ('work_accrued', 'Шахсий иш ҳисобланди'), ('material_shortage', 'Материал етишмовчилиги')], db_index=True, max_length=30, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
