# Generated by Django 5.1.15 on 2026-08-05 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_is_active_alter_company_name'),
        ('messaging', '0008_alter_chatmessage_company_alter_chatmessage_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WsTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ticket', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Тикет')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Действует до')),
                ('used', models.BooleanField(default=False, verbose_name='Использован')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ws_tickets', to='companies.company', verbose_name='Компания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ws_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'WS тикет',
                'verbose_name_plural': 'WS тикеты',
                'ordering': ['-created_at'],
            },
        ),
    ]
