# Generated by Django 5.1.15 on 2026-08-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0013_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_order', 'Янги буюртма'), ('new_expense', 'Янги харажат'), ('unpaid_client', 'Мижоз тўлов қилмади'), ('overdue_debt', 'Қарз муддати ўтди'), ('worker_refused', 'Ишчи рад этди'), ('work_awaiting', 'Иш тасдиқлашни кутмоқда'), ('cash_change', 'Касса ўзгариши'), ('report_ready', 'Ҳисобот тайёр'), ('task_assigned', 'Янги вазифа'), ('task_changed', 'Вазифа ўзгартирилди'), ('task_cancelled', 'Вазифа бекор қилинди'), ('work_confirmed', 'Иш тасдиқланди'), ('work_rejected', 'Иш рад этди'), ('new_message', 'Янги хабар'), ('work_accrued', 'Шахсий иш ҳисобланди'), ('material_shortage', 'Материал етишмовчилиги'), ('subscription_expiring_soon', 'Обуна 7 кундан сўнг тугайди'), ('subscription_expiring', 'Обуна 1 кундан сўнг тугайди'), ('subscription_frozen', 'Подписка истекла'), ('subscription_renewed', 'Подписка продлена'), ('subscription_renewal_request', 'Обунани узайтириш сўрови'), ('subscription_extended', 'Обуна узайтирилди'), ('subscription_grace_started', 'Имтиёзли давр бошланди'), ('subscription_expired', 'Обуна тугади'), ('subscription_plan_changed', 'Тариф ўзгартирилди')], db_index=True, max_length=30, verbose_name='Тип'),
        ),
    ]
