# Generated by Django 5.1.15 on 2026-09-07 10:49

import apps.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_seed_plans_and_trial_backfill'),
        ('messaging', '0015_alter_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat/attachments/%Y/%m/', validators=[apps.core.validators.validate_file_size, apps.core.validators.validate_attachment_extension], verbose_name='Вложение'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Имя файла'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Текст сообщения'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('content', ''), _negated=True), models.Q(('attachment__isnull', False), models.Q(('attachment', ''), _negated=True)), _connector='OR'), name='chatmessage_content_or_attachment'),
        ),
    ]
