# Generated by Django 5.1.15 on 2026-09-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0016_chatmessage_attachment_chatmessage_attachment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_key',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ключ текста'),
        ),
        migrations.AddField(
            model_name='notification',
            name='params',
            field=models.JSONField(blank=True, default=dict, verbose_name='Параметры текста'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_key',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ключ заголовка'),
        ),
    ]
