# Generated by Django 5.1.15 on 2026-08-15 14:50

import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_is_active_alter_company_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность'),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to='company_logos/', validators=[apps.core.validators.validate_file_size], verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_end',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Подписка до'),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Подписка с'),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Активна'), ('expired', 'Истекла'), ('frozen', 'Заморожена'), ('cancelled', 'Отменена')], db_index=True, default='active', max_length=20, verbose_name='Статус подписки'),
        ),
        migrations.CreateModel(
            name='SubscriptionChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('action', models.CharField(choices=[('activated', 'Активирована'), ('extended', 'Продлена'), ('end_set', 'Срок установлен'), ('frozen', 'Заморожена'), ('unfrozen', 'Разморожена'), ('expired', 'Истекла'), ('cancelled', 'Отменена')], db_index=True, max_length=20, verbose_name='Действие')),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='Было')),
                ('new_status', models.CharField(blank=True, max_length=20, verbose_name='Стало')),
                ('old_end', models.DateTimeField(blank=True, null=True, verbose_name='Было до')),
                ('new_end', models.DateTimeField(blank=True, null=True, verbose_name='Стало до')),
                ('days_added', models.PositiveIntegerField(blank=True, null=True, verbose_name='Добавлено дней')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_changes', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_changes', to='companies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Изменение подписки',
                'verbose_name_plural': 'История подписок',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'created_at'], name='companies_s_company_fd9e3a_idx')],
            },
        ),
    ]
