# Generated by Django 5.1.15 on 2026-08-15 18:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_subscription_expiry_notify_beat'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Код')),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='Длительность (дней)')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Цена')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('limits', models.JSONField(blank=True, default=dict, verbose_name='Ограничения')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы подписки',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='grace_period_days',
            field=models.PositiveSmallIntegerField(default=7, verbose_name='Льготный период (дней)'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_trial',
            field=models.BooleanField(default=True, verbose_name='Триал'),
        ),
        migrations.AddField(
            model_name='subscriptionchange',
            name='new_plan',
            field=models.CharField(blank=True, max_length=100, verbose_name='Стал тариф'),
        ),
        migrations.AddField(
            model_name='subscriptionchange',
            name='old_plan',
            field=models.CharField(blank=True, max_length=100, verbose_name='Был тариф'),
        ),
        migrations.AlterField(
            model_name='company',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Активна'), ('grace', 'Льготный период'), ('expired', 'Истекла'), ('frozen', 'Заморожена'), ('cancelled', 'Отменена')], db_index=True, default='active', max_length=20, verbose_name='Статус подписки'),
        ),
        migrations.AlterField(
            model_name='subscriptionchange',
            name='action',
            field=models.CharField(choices=[('activated', 'Активирована'), ('extended', 'Продлена'), ('end_set', 'Срок установлен'), ('grace_started', 'Льготный период начался'), ('frozen', 'Заморожена'), ('unfrozen', 'Разморожена'), ('expired', 'Истекла'), ('plan_changed', 'Тариф изменён'), ('cancelled', 'Отменена')], db_index=True, max_length=20, verbose_name='Действие'),
        ),
        migrations.AddField(
            model_name='company',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='companies.subscriptionplan', verbose_name='Тариф'),
        ),
    ]
