# Generated by Django 5.1.15 on 2026-09-08 05:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_seed_plans_and_trial_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='min_work_photos',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Минимум фото при сдаче работы'),
        ),
    ]
