# Generated by Django 5.2.16 on 2026-08-16 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_alter_company_is_active_alter_company_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', max_length=10, verbose_name='Тариф')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('frozen', 'Frozen')], db_index=True, default='active', max_length=10, verbose_name='Статус')),
                ('started_at', models.DateTimeField(verbose_name='Начало периода')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Действует до')),
                ('last_renewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее продление')),
                ('frozen_at', models.DateTimeField(blank=True, null=True, verbose_name='Заморожена')),
                ('last_reminder_at', models.DateTimeField(blank=True, null=True, verbose_name='Напоминание отправлено')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='companies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['-expires_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма')),
                ('currency', models.CharField(default='UZS', max_length=3, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('failed', 'Ошибка'), ('cancelled', 'Отменён')], db_index=True, default='pending', max_length=10, verbose_name='Статус')),
                ('provider', models.CharField(default='manual', max_length=20, verbose_name='Платёжный провайдер')),
                ('provider_payment_id', models.CharField(blank=True, default='', max_length=128, verbose_name='ID платежа провайдера')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачен когда')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='companies.company', verbose_name='Компания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.subscription', verbose_name='Подписка')),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'Счета',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subscription', 'status'], name='billing_inv_subscri_4c8e1f_idx'), models.Index(fields=['company', 'status'], name='billing_inv_company_b457aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Создана'), ('activated', 'Активирована'), ('renewed', 'Продлена'), ('extended', 'Продлена супер-админом'), ('expired', 'Истекла'), ('frozen', 'Заморожена'), ('unfrozen', 'Разморожена'), ('plan_changed', 'Тариф изменён'), ('invoice_paid', 'Счёт оплачен')], max_length=20, verbose_name='Действие')),
                ('actor_role', models.CharField(blank=True, max_length=20, verbose_name='Роль исполнителя')),
                ('from_status', models.CharField(blank=True, max_length=10, verbose_name='Было')),
                ('to_status', models.CharField(blank=True, max_length=10, verbose_name='Стало')),
                ('old_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Было до')),
                ('new_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Стало до')),
                ('note', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто выполнил')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_events', to='companies.company', verbose_name='Компания')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='billing.subscription', verbose_name='Подписка')),
            ],
            options={
                'verbose_name': 'Событие подписки',
                'verbose_name_plural': 'История подписок',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subscription', 'created_at'], name='billing_sub_subscri_924d42_idx'), models.Index(fields=['company', 'created_at'], name='billing_sub_company_55ae0f_idx')],
            },
        ),
    ]
