# Generated by Django 5.1.15 on 2026-07-12 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('rent', 'Ижара'), ('electricity', 'Электр энергия'), ('water', 'Сув'), ('transport', 'Транспорт'), ('delivery', 'Етказиб бериш'), ('taxes', 'Солиқлар'), ('salary', 'Ишчилар иш ҳақи'), ('advance', 'Ишчиларга аванс'), ('equipment_repair', 'Ускуна таъмири'), ('tools', 'Асбоб сотиб олиш'), ('consumables', 'Сарфлаш материаллари'), ('material_loss', 'Материал йўқотиш'), ('defect', 'Брак'), ('unforeseen', 'Кутилмаган харажатлар'), ('owner_withdrawal', 'Эгасининг шахсий чиқими'), ('worker_debt', 'Ишчилар қарзлари'), ('client_refund', 'Мижозларга қайтариш'), ('other', 'Бошқа')], db_index=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField(db_index=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('receipt_photo', models.ImageField(blank=True, null=True, upload_to='finance/receipts/')),
                ('payment_method', models.CharField(choices=[('cash', 'Нақд'), ('card', 'Карта'), ('transfer', 'Ўтказма'), ('other', 'Бошқа')], default='cash', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['category', 'date'], name='finance_exp_categor_576c9a_idx'), models.Index(fields=['date'], name='finance_exp_date_677539_idx')],
            },
        ),
        migrations.CreateModel(
            name='LaborRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.CharField(choices=[('cutting', 'Кесиш'), ('polishing', 'Сийлаш'), ('mounting', 'Монтаж'), ('packing', 'Қутлаш'), ('other', 'Бошқа')], max_length=20)),
                ('rate_per_unit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit', models.CharField(choices=[('sht', 'Штук'), ('m', 'Метр'), ('m2', 'Квадратный метр'), ('izdelie', 'Изделие'), ('dona', 'Дона')], max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_rates', to='warehouse.finishedproduct')),
            ],
            options={
                'verbose_name': 'Labor Rate',
                'verbose_name_plural': 'Labor Rates',
                'ordering': ['product', 'operation'],
                'unique_together': {('product', 'operation')},
            },
        ),
        migrations.CreateModel(
            name='WorkerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_date', models.DateField(db_index=True)),
                ('payment_type', models.CharField(choices=[('salary', 'Иш ҳақи'), ('advance', 'Аванс'), ('bonus', 'Мукофот'), ('other', 'Бошқа')], default='salary', max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Worker Payment',
                'verbose_name_plural': 'Worker Payments',
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['worker', 'payment_date'], name='finance_wor_worker__61b3bd_idx'), models.Index(fields=['payment_date'], name='finance_wor_payment_b18f91_idx')],
            },
        ),
    ]
