# Generated by Django 5.1.4 on 2026-07-10 11:42

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('warehouse', '0002_alter_finishedproduct_cost_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='laborrate',
            name='rate_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='workerpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='expense_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='laborrate',
            constraint=models.CheckConstraint(condition=models.Q(('rate_per_unit__gte', 0)), name='labor_rate_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='workerpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='worker_payment_amount_non_negative'),
        ),
    ]
