# Generated by Django 5.1.15 on 2026-07-16 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_expense_created_at_alter_expense_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Расход', 'verbose_name_plural': 'Расходы'},
        ),
        migrations.AlterModelOptions(
            name='laborrate',
            options={'ordering': ['product', 'operation'], 'verbose_name': 'Ставка оплаты труда', 'verbose_name_plural': 'Ставки оплаты труда'},
        ),
        migrations.AlterModelOptions(
            name='workerpayment',
            options={'ordering': ['-payment_date', '-created_at'], 'verbose_name': 'Выплата работнику', 'verbose_name_plural': 'Выплаты работникам'},
        ),
    ]
