# Generated by Django 5.1.15 on 2026-07-20 14:40

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_expense_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='receipt_photo',
            field=models.ImageField(blank=True, null=True, upload_to='finance/receipts/', validators=[apps.core.validators.validate_file_size]),
        ),
    ]
