# Generated by Django 5.1.15 on 2026-07-27 11:44

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_is_active_alter_company_name'),
        ('finance', '0007_alter_expense_amount_alter_laborrate_rate_per_unit_and_more'),
        ('warehouse', '0006_alter_finishedproduct_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('rent', 'Ижара'), ('electricity', 'Электр энергия'), ('water', 'Сув'), ('transport', 'Транспорт'), ('delivery', 'Етказиб бериш'), ('taxes', 'Солиқлар'), ('salary', 'Ишчилар иш ҳақи'), ('advance', 'Ишчиларга аванс'), ('equipment_repair', 'Ускуна таъмири'), ('tools', 'Асбоб сотиб олиш'), ('consumables', 'Сарфлаш материаллари'), ('material_loss', 'Материал йўқотиш'), ('defect', 'Брак'), ('unforeseen', 'Кутилмаган харажатлар'), ('owner_withdrawal', 'Эгасининг шахсий чиқими'), ('worker_debt', 'Ишчилар қарзлари'), ('client_refund', 'Мижозларга қайтариш'), ('other', 'Бошқа')], db_index=True, max_length=30, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Нақд'), ('card', 'Карта'), ('transfer', 'Ўтказма'), ('other', 'Бошқа')], default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='receipt_photo',
            field=models.ImageField(blank=True, null=True, upload_to='finance/receipts/', validators=[apps.core.validators.validate_file_size], verbose_name='Фото чека'),
        ),
        migrations.AlterField(
            model_name='laborrate',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labor_rates', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='laborrate',
            name='operation',
            field=models.CharField(choices=[('cutting', 'Кесиш'), ('polishing', 'Сийлаш'), ('mounting', 'Монтаж'), ('packing', 'Қутлаш'), ('other', 'Бошқа')], max_length=20, verbose_name='Операция'),
        ),
        migrations.AlterField(
            model_name='laborrate',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_rates', to='warehouse.finishedproduct', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='laborrate',
            name='rate_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ставка за единицу'),
        ),
        migrations.AlterField(
            model_name='laborrate',
            name='unit',
            field=models.CharField(choices=[('sht', 'Штук'), ('m', 'Метр'), ('m2', 'Квадратный метр'), ('izdelie', 'Изделие'), ('dona', 'Дона')], max_length=20, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='workerpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='workerpayment',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='workerpayment',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_payments', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='workerpayment',
            name='payment_date',
            field=models.DateField(db_index=True, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='workerpayment',
            name='payment_type',
            field=models.CharField(choices=[('salary', 'Иш ҳақи'), ('advance', 'Аванс'), ('bonus', 'Мукофот'), ('other', 'Бошқа')], default='salary', max_length=20, verbose_name='Вид выплаты'),
        ),
        migrations.AlterField(
            model_name='workerpayment',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Работник'),
        ),
    ]
