# Generated by Django 5.1.15 on 2026-07-28 06:06

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_expense_amount_alter_expense_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(db_index=True, validators=[apps.core.validators.validate_not_future], verbose_name='Дата'),
        ),
    ]
