# Generated by Django 5.1.15 on 2026-08-05 07:45

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_laborrate_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerpayment',
            name='payment_date',
            field=models.DateField(db_index=True, validators=[apps.core.validators.validate_not_future], verbose_name='Дата оплаты'),
        ),
    ]
