# Generated by Django 5.1.15 on 2026-08-05 09:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_workerpayment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborrate',
            name='rate_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ставка за единицу'),
        ),
    ]
