# Generated by Django 5.1.15 on 2026-09-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_laborrate_rate_per_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborrate',
            name='unit',
            field=models.CharField(choices=[('sht', 'Штук'), ('m', 'Метр'), ('m2', 'Квадратный метр'), ('izdelie', 'Изделие'), ('kg', 'Килограмм'), ('m3', 'Кубический метр')], max_length=20, verbose_name='Единица измерения'),
        ),
    ]
