# Generated by Django 5.2.17 on 2026-09-14 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_laborrate_unit'),
        ('orders', '0015_alter_order_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_expenses', to='orders.order', verbose_name='Заказ'),
        ),
    ]
