# Generated by Django 5.1.15 on 2026-07-25 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_alter_company_options_alter_company_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('success', 'Успешно'), ('failed', 'Ошибка')], default='running', max_length=10, verbose_name='Статус')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='Имя файла')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Размер (байт)')),
                ('storage', models.CharField(blank=True, max_length=20, verbose_name='Хранилище')),
                ('s3_key', models.CharField(blank=True, max_length=500, verbose_name='S3 Key')),
                ('telegram_message_id', models.CharField(blank=True, max_length=100, verbose_name='Telegram Message ID')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='Длительность (сек)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_logs', to='companies.company', verbose_name='Компания')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_backups', to=settings.AUTH_USER_MODEL, verbose_name='Запущен пользователем')),
            ],
            options={
                'verbose_name': 'Лог бэкапа',
                'verbose_name_plural': 'Логи бэкапов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Авто-бэкап включён')),
                ('schedule', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], default='daily', max_length=10, verbose_name='Расписание')),
                ('storage', models.CharField(choices=[('s3', 'S3 (AWS / MinIO)'), ('telegram', 'Telegram'), ('both', 'S3 + Telegram')], default='s3', max_length=10, verbose_name='Хранилище')),
                ('keep_last', models.PositiveIntegerField(default=7, help_text='Количество последних бэкапов', verbose_name='Хранить последних')),
                ('s3_endpoint', models.CharField(blank=True, default='', max_length=255, verbose_name='S3 Endpoint')),
                ('s3_region', models.CharField(blank=True, default='', max_length=100, verbose_name='S3 Region')),
                ('s3_bucket', models.CharField(blank=True, default='skladpro-backups', max_length=255, verbose_name='S3 Bucket')),
                ('s3_access_key', models.CharField(blank=True, default='', max_length=255, verbose_name='S3 Access Key')),
                ('s3_secret_key', models.CharField(blank=True, default='', max_length=255, verbose_name='S3 Secret Key')),
                ('s3_path_prefix', models.CharField(blank=True, default='backups/', max_length=255, verbose_name='S3 Path Prefix')),
                ('telegram_bot_token', models.CharField(blank=True, default='', max_length=255, verbose_name='Telegram Bot Token')),
                ('telegram_chat_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Telegram Chat ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_configs', to='companies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Настройка бэкапа',
                'verbose_name_plural': 'Настройки бэкапа',
                'constraints': [models.UniqueConstraint(fields=('company',), name='backup_single_config_per_company')],
            },
        ),
    ]
