# Generated by Django 5.1.15 on 2026-07-26 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
        ('companies', '0003_alter_company_options_alter_company_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupconfig',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup_configs', to='companies.company', verbose_name='Компания (null = платформа)'),
        ),
        migrations.AlterField(
            model_name='backuplog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup_logs', to='companies.company', verbose_name='Компания (null = платформа)'),
        ),
    ]
