# Generated by Django 5.1.15 on 2026-07-16 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_currency_created_at_alter_currency_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['-is_default', 'code'], 'verbose_name': 'Валюта', 'verbose_name_plural': 'Валюты'},
        ),
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ['-effective_date'], 'verbose_name': 'Курс валют', 'verbose_name_plural': 'Курсы валют'},
        ),
    ]
