# Generated by Django 5.1.15 on 2026-07-27 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_currency_options_alter_exchangerate_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(help_text='ISO 4217 code (e.g. KGS, USD)', max_length=3, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='decimal_places',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Знаков после запятой'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Валюта по умолчанию'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(help_text='Currency name', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(help_text='Currency symbol', max_length=10, verbose_name='Символ'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='effective_date',
            field=models.DateField(db_index=True, verbose_name='Действует с'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='from_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='core.currency', verbose_name='Из валюты'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=6, help_text='Exchange rate', max_digits=12, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='to_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='core.currency', verbose_name='В валюту'),
        ),
    ]
