# Generated by Django 5.1.4 on 2026-07-10 11:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedproduct',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='min_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='reserved_for_orders',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='avg_cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='min_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='quantity_required',
            field=models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='warehouse.rawmaterial'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='warehouse.finishedproduct'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AddConstraint(
            model_name='finishedproduct',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='finished_product_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='finishedproduct',
            constraint=models.CheckConstraint(condition=models.Q(('min_stock__gte', 0)), name='finished_product_min_stock_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='finishedproduct',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_for_orders__gte', 0)), name='finished_product_reserved_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='finishedproduct',
            constraint=models.CheckConstraint(condition=models.Q(('cost_price__gte', 0)), name='finished_product_cost_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='finishedproduct',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price__gte', 0)), name='finished_product_sale_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='rawmaterial',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='raw_material_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='rawmaterial',
            constraint=models.CheckConstraint(condition=models.Q(('min_stock__gte', 0)), name='raw_material_min_stock_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='rawmaterial',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_price__gte', 0)), name='raw_material_purchase_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='rawmaterial',
            constraint=models.CheckConstraint(condition=models.Q(('avg_cost_price__gte', 0)), name='raw_material_avg_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='recipeitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_required__gt', 0)), name='recipe_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='stock_movement_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('price_per_unit__gte', 0)), name='stock_movement_price_non_negative'),
        ),
    ]
