# Generated by Django 5.1.15 on 2026-07-16 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_finishedproduct_archived_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finishedproduct',
            options={'ordering': ['name'], 'verbose_name': 'Готовая продукция', 'verbose_name_plural': 'Готовая продукция'},
        ),
        migrations.AlterModelOptions(
            name='rawmaterial',
            options={'ordering': ['name'], 'verbose_name': 'Сырьё (материал)', 'verbose_name_plural': 'Склад сырья'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['name'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='recipeitem',
            options={'verbose_name': 'Компонент рецепта', 'verbose_name_plural': 'Компоненты рецепта'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Движение склада', 'verbose_name_plural': 'Движения склада'},
        ),
    ]
