# Generated by Django 5.1.15 on 2026-07-20 14:40

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_finishedproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedproduct',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='products/', validators=[apps.core.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='materials/', validators=[apps.core.validators.validate_file_size]),
        ),
    ]
