# Generated by Django 5.1.15 on 2026-07-27 11:44

import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_is_active_alter_company_name'),
        ('warehouse', '0005_alter_finishedproduct_photo_alter_rawmaterial_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedproduct',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finished_products', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Себестоимость'),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='min_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Минимальный остаток'),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='products/', validators=[apps.core.validators.validate_file_size], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='reserved_for_orders',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Зарезервировано под заказы'),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена продажи'),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='unit',
            field=models.CharField(choices=[('sht', 'Штук'), ('m', 'Метр'), ('m2', 'Квадратный метр'), ('izdelie', 'Изделие'), ('dona', 'Дона')], default='izdelie', max_length=20, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата поступления'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='avg_cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Средняя себестоимость'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='color',
            field=models.CharField(blank=True, max_length=100, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='min_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Минимальный остаток'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='materials/', validators=[apps.core.validators.validate_file_size], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена закупки'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='size',
            field=models.CharField(blank=True, max_length=100, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='stone_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Вид камня'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='storage_location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место хранения'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='thickness',
            field=models.CharField(blank=True, max_length=50, verbose_name='Толщина'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='unit',
            field=models.CharField(choices=[('sht', 'Штук'), ('m', 'Метр'), ('m2', 'Квадратный метр'), ('izdelie', 'Изделие'), ('dona', 'Дона')], default='sht', max_length=20, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='warehouse.finishedproduct', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='warehouse.rawmaterial', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='quantity_required',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Требуемое количество'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='unit',
            field=models.CharField(choices=[('sht', 'Штук'), ('m', 'Метр'), ('m2', 'Квадратный метр'), ('izdelie', 'Изделие'), ('dona', 'Дона')], default='sht', max_length=20, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='warehouse.rawmaterial', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('incoming', 'Приход'), ('outgoing', 'Расход'), ('production_in', 'Приход с производства'), ('production_out', 'Расход на производство'), ('adjustment', 'Корректировка'), ('loss', 'Потеря/Брак')], db_index=True, max_length=20, verbose_name='Тип движения'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='warehouse.finishedproduct', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='related_order_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID связанного заказа'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='related_production_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID связанного производства'),
        ),
    ]
