# Generated by Django 5.1.15 on 2026-07-28 06:06

import apps.core.validators
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_alter_finishedproduct_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedproduct',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Себестоимость'),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='reserved_for_orders',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Зарезервировано под заказы'),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена продажи'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='arrival_date',
            field=models.DateField(blank=True, null=True, validators=[apps.core.validators.validate_not_future], verbose_name='Дата поступления'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='avg_cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Средняя себестоимость'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='min_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Минимальный остаток'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена закупки'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Количество'),
        ),
    ]
