# Generated by Django 5.1.15 on 2026-08-01 17:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_alter_finishedproduct_unit_alter_rawmaterial_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='Штрихкод'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='reserved_for_orders',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Зарезервировано под заказы'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='storage_zone',
            field=models.CharField(blank=True, choices=[('a', 'А зона'), ('b', 'Б зона'), ('c', 'В зона'), ('other', 'Бошқа')], default='', max_length=10, verbose_name='Зона хранения'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='document_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Номер документа'),
        ),
    ]
