# Generated by Django 5.1.15 on 2026-08-05 08:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_rawmaterial_barcode_rawmaterial_reserved_for_orders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedproduct',
            name='min_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Минимальный остаток'),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Количество'),
        ),
    ]
