# Generated by Django 5.1.15 on 2026-08-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_seed_plans_and_trial_backfill'),
        ('warehouse', '0012_alter_recipeitem_quantity_required'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='finishedproduct',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='finishedproduct_quantity_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='finishedproduct',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_for_orders__gte', 0)), name='finishedproduct_reserved_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='finishedproduct',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_for_orders__lte', models.F('quantity'))), name='finishedproduct_reserved_lte_quantity'),
        ),
        migrations.AddConstraint(
            model_name='rawmaterial',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='rawmaterial_quantity_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='rawmaterial',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_for_orders__gte', 0)), name='rawmaterial_reserved_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='rawmaterial',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_for_orders__lte', models.F('quantity'))), name='rawmaterial_reserved_lte_quantity'),
        ),
    ]
