# Generated by Django 5.1.15 on 2026-09-07 13:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_seed_plans_and_trial_backfill'),
        ('warehouse', '0016_drop_stale_rawmaterial_reserved_lte_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='occupied_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Занимает площади, м²'),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_archived', models.BooleanField(db_index=True, default=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата архивации')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('code', models.CharField(blank=True, default='', max_length=30, verbose_name='Код')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес')),
                ('total_area', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Общая площадь, м²')),
                ('is_default', models.BooleanField(default=False, verbose_name='Склад по умолчанию')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='companies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='warehouse.warehouse', verbose_name='Склад'),
        ),
        migrations.CreateModel(
            name='WarehouseCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_archived', models.BooleanField(db_index=True, default=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата архивации')),
                ('code', models.CharField(max_length=20, verbose_name='Код ячейки')),
                ('zone', models.CharField(blank=True, choices=[('a', 'А зона'), ('b', 'Б зона'), ('c', 'В зона'), ('other', 'Бошқа')], default='', max_length=10, verbose_name='Зона')),
                ('capacity_area', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Вместимость, м²')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_cells', to='companies.company', verbose_name='Компания')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='warehouse.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Ячейка хранения',
                'verbose_name_plural': 'Ячейки хранения',
                'ordering': ['warehouse', 'code'],
            },
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='warehouse.warehousecell', verbose_name='Ячейка хранения'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='warehouse_unique_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('company',), name='warehouse_single_default_per_company'),
        ),
        migrations.AddConstraint(
            model_name='warehousecell',
            constraint=models.UniqueConstraint(fields=('warehouse', 'code'), name='cell_unique_code_per_warehouse'),
        ),
    ]
