# Generated by Django 5.1.15 on 2026-09-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0018_default_warehouse_per_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='condition',
            field=models.CharField(blank=True, choices=[('excellent', 'Отличное'), ('good', 'Хорошее'), ('poor', 'Ниже среднего'), ('critical', 'Критическое')], default='', max_length=20, verbose_name='Состояние материала'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('incoming', 'Приход'), ('outgoing', 'Расход'), ('production_in', 'Приход с производства'), ('production_out', 'Расход на производство'), ('adjustment', 'Корректировка'), ('loss', 'Потеря/Брак'), ('return', 'Возврат')], db_index=True, max_length=20, verbose_name='Тип движения'),
        ),
    ]
