# Generated by Django 5.1.15 on 2026-09-08 04:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0019_rawmaterial_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='code',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Код рецепта'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='output_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Выход готовой продукции'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='size',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Размер изделия'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='thickness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Толщина, мм'),
        ),
    ]
