# Generated by Django 5.1.15 on 2026-09-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0020_recipe_code_recipe_output_quantity_recipe_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='purpose',
            field=models.CharField(blank=True, choices=[('production', 'Производство'), ('sample', 'Образец'), ('internal', 'Внутренние нужды'), ('write_off', 'Списание'), ('other', 'Другое')], default='', max_length=20, verbose_name='Назначение расхода'),
        ),
    ]
