# Generated by Django 5.1.15 on 2026-09-08 05:27

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_seed_plans_and_trial_backfill'),
        ('warehouse', '0021_stockmovement_purpose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('supplier', models.CharField(blank=True, default='', max_length=255, verbose_name='Поставщик')),
                ('document_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Номер документа')),
                ('receipt_date', models.DateField(blank=True, null=True, validators=[apps.core.validators.validate_not_future], verbose_name='Дата прихода')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipts', to='companies.company', verbose_name='Компания')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан')),
            ],
            options={
                'verbose_name': 'Документ прихода',
                'verbose_name_plural': 'Документы прихода',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='warehouse.goodsreceipt', verbose_name='Документ прихода'),
        ),
        migrations.CreateModel(
            name='GoodsReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Количество')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена за единицу')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='receipt_lines', to='warehouse.rawmaterial', verbose_name='Материал')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='warehouse.goodsreceipt', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Позиция прихода',
                'verbose_name_plural': 'Позиции прихода',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='goodsreceipt',
            constraint=models.UniqueConstraint(condition=models.Q(('document_number', ''), _negated=True), fields=('company', 'supplier', 'document_number'), name='goods_receipt_unique_document'),
        ),
    ]
