# Generated by Django 5.1.15 on 2026-09-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0026_merge_dona_into_sht'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedproduct',
            name='unit',
            field=models.CharField(choices=[('sht', 'Штук'), ('m', 'Метр'), ('m2', 'Квадратный метр'), ('izdelie', 'Изделие'), ('kg', 'Килограмм'), ('m3', 'Кубический метр')], default='izdelie', max_length=20, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='unit',
            field=models.CharField(choices=[('sht', 'Штук'), ('m', 'Метр'), ('m2', 'Квадратный метр'), ('izdelie', 'Изделие'), ('kg', 'Килограмм'), ('m3', 'Кубический метр')], default='sht', max_length=20, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='unit',
            field=models.CharField(choices=[('sht', 'Штук'), ('m', 'Метр'), ('m2', 'Квадратный метр'), ('izdelie', 'Изделие'), ('kg', 'Килограмм'), ('m3', 'Кубический метр')], default='sht', max_length=20, verbose_name='Единица измерения'),
        ),
    ]
