# Generated by Django 5.1.15 on 2026-09-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0027_alter_finishedproduct_unit_alter_rawmaterial_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='storage_zone',
            field=models.CharField(blank=True, choices=[('a', 'А зона'), ('b', 'Б зона'), ('c', 'В зона'), ('d', 'Г зона'), ('other', 'Бошқа')], default='', max_length=10, verbose_name='Зона хранения'),
        ),
        migrations.AlterField(
            model_name='warehousecell',
            name='zone',
            field=models.CharField(blank=True, choices=[('a', 'А зона'), ('b', 'Б зона'), ('c', 'В зона'), ('d', 'Г зона'), ('other', 'Бошқа')], default='', max_length=10, verbose_name='Зона'),
        ),
    ]
