# Generated by Django 5.1.15 on 2026-07-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditlog_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('setup_owner', 'Setup owner'), ('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('archive', 'Archive'), ('delete', 'Delete'), ('activate', 'Activate'), ('deactivate', 'Deactivate'), ('reset_password', 'Reset password'), ('change_password', 'Change password'), ('change_language', 'Change language')], db_index=True, max_length=50),
        ),
    ]
