# Generated by Django 5.1.15 on 2026-07-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('setup_owner', 'Setup owner'), ('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('archive', 'Archive'), ('delete', 'Delete'), ('activate', 'Activate'), ('deactivate', 'Deactivate'), ('reset_password', 'Reset password'), ('change_password', 'Change password'), ('change_language', 'Change language'), ('access_key_issued', 'Access key issued'), ('access_key_redeemed', 'Access key redeemed'), ('access_key_revoked', 'Access key revoked')], db_index=True, max_length=50),
        ),
    ]
