# Generated by Django 5.1.15 on 2026-07-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_alter_auditlog_options_alter_auditlog_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('setup_owner', 'Создание супер-админа'), ('login', 'Вход'), ('logout', 'Выход'), ('create', 'Создание'), ('update', 'Изменение'), ('archive', 'Архивация'), ('delete', 'Удаление'), ('activate', 'Разблокировка'), ('deactivate', 'Блокировка'), ('reset_password', 'Сброс пароля'), ('change_password', 'Смена пароля'), ('change_language', 'Смена языка'), ('access_key_issued', 'Код доступа выдан'), ('access_key_redeemed', 'Код доступа активирован'), ('access_key_revoked', 'Код доступа отозван')], db_index=True, max_length=50),
        ),
    ]
