# Generated by Django 5.1.15 on 2026-07-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('setup_owner', 'Создание супер-админа'), ('login', 'Вход'), ('logout', 'Выход'), ('create', 'Создание'), ('update', 'Изменение'), ('archive', 'Архивация'), ('delete', 'Удаление'), ('activate', 'Разблокировка'), ('deactivate', 'Блокировка'), ('reset_password', 'Сброс пароля'), ('change_password', 'Смена пароля'), ('change_language', 'Смена языка'), ('access_key_issued', 'Код доступа выдан'), ('access_key_redeemed', 'Код доступа активирован'), ('access_key_revoked', 'Код доступа отозван'), ('two_factor_enabled', 'Двухэтапное подтверждение включено'), ('two_factor_disabled', 'Двухэтапное подтверждение выключено'), ('two_factor_failed', 'Неверный код подтверждения'), ('two_factor_recovery_used', 'Использован резервный код'), ('two_factor_recovery_regenerated', 'Резервные коды перевыпущены'), ('token_theft_detected', 'Обнаружена кража токена')], db_index=True, max_length=50),
        ),
    ]
