# Generated by Django 5.1.15 on 2026-07-27 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_alter_auditlog_action'),
        ('companies', '0004_alter_company_is_active_alter_company_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('setup_owner', 'Создание супер-админа'), ('login', 'Вход'), ('logout', 'Выход'), ('create', 'Создание'), ('update', 'Изменение'), ('archive', 'Архивация'), ('delete', 'Удаление'), ('activate', 'Разблокировка'), ('deactivate', 'Блокировка'), ('reset_password', 'Сброс пароля'), ('change_password', 'Смена пароля'), ('change_language', 'Смена языка'), ('access_key_issued', 'Код доступа выдан'), ('access_key_redeemed', 'Код доступа активирован'), ('access_key_revoked', 'Код доступа отозван'), ('two_factor_enabled', 'Двухэтапное подтверждение включено'), ('two_factor_disabled', 'Двухэтапное подтверждение выключено'), ('two_factor_failed', 'Неверный код подтверждения'), ('two_factor_recovery_used', 'Использован резервный код'), ('two_factor_recovery_regenerated', 'Резервные коды перевыпущены'), ('token_theft_detected', 'Обнаружена кража токена')], db_index=True, max_length=50, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Кто выполнил'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor_role',
            field=models.CharField(blank=True, max_length=20, verbose_name='Роль исполнителя'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor_username',
            field=models.CharField(blank=True, max_length=150, verbose_name='Логин исполнителя'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='changes',
            field=models.JSONField(blank=True, default=dict, verbose_name='Изменения'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='ID объекта'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_repr',
            field=models.CharField(blank=True, max_length=255, verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_type',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Тип объекта'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='Устройство'),
        ),
    ]
