# Generated by Django 5.1.15 on 2026-07-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
