# Generated by Django 5.1.15 on 2026-07-28 06:06

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_client_address_alter_client_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=50, validators=[apps.core.validators.validate_phone], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(db_index=True, validators=[apps.core.validators.validate_not_future], verbose_name='Дата оплаты'),
        ),
    ]
