# Generated by Django 5.1.15 on 2026-08-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_client_phone_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Нақд'), ('card', 'Карта'), ('transfer', 'Ўтказма'), ('other', 'Бошқа')], default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
