# Generated by Django 5.1.15 on 2026-09-08 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_payment_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('individual', 'Жисмоний шахс'), ('company', 'Юридик шахс')], default='individual', max_length=20, verbose_name='Тип клиента'),
        ),
        migrations.AddField(
            model_name='client',
            name='responsible_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_clients', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный сотрудник'),
        ),
    ]
